version: 1.2.{build}
branches:
  only:
  - master
skip_non_tags: true
configuration: Release
platform: Any CPU
clone_depth: 3
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: VDZFDL3VGpSW2ZInor2BOBJx3A4vFzp+dNBx9KHvRcc+Jhj7kbzUII4gRlrPgBx5
